services:
  - type: web
    name: vvfirefly-backend
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
